### ISSUE TITLE
Mozilla - Disabled day

### ISSUE THREAD

**Issue by erollmaxhuni** [angliafarmers/ember-material-design-datepicker#38]
well this part of code is not working in mozilla

`let disabled = false;
      if (minDate && this.getMoment(minDate).isAfter(date, 'day')) {
        disabled = true;
      }
      else if (maxDate && this.getMoment(maxDate).isBefore(date, 'day')) {
        disabled = true;
      }`

**Comment by adam-knights** [comment]
@adamlawson I remember some changes in that area for 1.1? Can you take a look?

**Comment by adaml881** [comment]
@erollmaxhuni Thanks for reporting. I've just tested in Firefox 47.0.1 and it works fine. Do you have an error message or are you seeing unexpected behaviour?

There was a CSS update relating to the disabled dates in a recent update so perhaps your browser still has the old CSS cached?

**Comment by adam-knights** [comment]
Closing this, feel free to reopen if you can provide a reproduction or more information on what is not working.

**Comment by erollmaxhuni** [comment]
@adam-knights @adamlawson @adam-knights  thank you all it was working everything with recent releases
